import { useState } from "react"
import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
// import styles from "@/styles/Home.module.css"
import { AccordionItem, ExclusiveAccordion } from "@reusable-ui/exclusive-accordion"
import '@cssfn/cssfn-dom'

const inter = Inter({ subsets: ["latin"] });



interface ParagraphLoremProps {
    words? : number
}
const lorems = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem accusantium et ipsam, architecto cupiditate recusandae dolorem itaque tempore expedita commodi eos doloremque molestias. Impedit doloribus maxime rem, iste quia consequuntur?'.split(' ');
const ParagraphLorem = ({ words }: ParagraphLoremProps) => (
    <p>
        { (words ? lorems.slice(0, words) : lorems).join(' ') }
    </p>
);



export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.className}`}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea inventore debitis, tempore sapiente possimus ratione velit voluptatibus quidem accusamus odio illo voluptate esse delectus et fugiat voluptatum voluptatem. Fuga, provident.</p>
                <ExclusiveAccordion theme='primary' defaultExpandedListIndex={1}>
                    <AccordionItem key={0} expanded={undefined} onExpandedChange={undefined} label='A first item'>
                        <p>The detail of first item.</p>
                        <ParagraphLorem />
                        <ParagraphLorem />
                    </AccordionItem>
                    <AccordionItem key={1} label='A second item' className='fluid'>
                        <p>The detail of second item.</p>
                        <ParagraphLorem />
                        <ParagraphLorem />
                    </AccordionItem>
                    <AccordionItem key={2} label='A third item' theme='success'>
                        <p>The detail of third item.</p>
                        <ParagraphLorem />
                        <ParagraphLorem />
                    </AccordionItem>
                    <AccordionItem key={3} label='A fourth item' defaultExpanded={true}>
                        <p>The detail of fourth item.</p>
                        <ParagraphLorem />
                        <ParagraphLorem />
                    </AccordionItem>
                    <AccordionItem key={4} label='A fifth item' theme='danger'>
                        <p>The detail of fifth item.</p>
                        <ParagraphLorem />
                        <ParagraphLorem />
                    </AccordionItem>
                </ExclusiveAccordion>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea inventore debitis, tempore sapiente possimus ratione velit voluptatibus quidem accusamus odio illo voluptate esse delectus et fugiat voluptatum voluptatem. Fuga, provident.</p>
            </main>
        </>
    );
}
