export const domainOrder = new Set<string>([
// Configs:
'colorConfig',
'colorParamConfig',
'borderConfig',
'borderRadiusConfig',
'spacerConfig',
'breakpointConfig',
'typoConfig',
'secondaryConfig',
'paragraphConfig',
'leadConfig',
'headingConfig',
'displayConfig',
'blockquoteConfig',
'plainListConfig',
'markConfig',
'kbdConfig',
'codeConfig',
'horzSeparatorConfig',
'vertSeparatorConfig',

// Variants:
'orientationVariant',
'flowDirectionVariant',
'sizeVariant',
'themeVariant',
'emphasisVariant',
'outlineVariant',
'mildVariant',
'bareVariant',

// Features:
'backgroundFeature',
'foregroundFeature',
'decorationFeature',
'borderFeature',
'ringFeature',
'paddingFeature',
'animationFeature',
'filterFeature',
'transformFeature',
'shadowFeature',

// States:
'disabledState',
'readOnlyState',
'focusState',
'hoverState',
'pressState',
'validityState',
'dragState',
'sortState',
'exciteState',
'collapseState',
'activeState',
'viewState',

// Effects:
'disabledEffect',
'readOnlyEffect',
'focusEffect',
'hoverEffect',
'pressEffect',
'validityEffect',
'dragEffect',
'sortEffect',
'exciteEffect',
'collapseEffect',
'activeEffect',
'viewEffect',
]);